### ISSUE TITLE
Change request - Cache-in outputmanagement

### ISSUE THREAD

**Issue by hubertguillemain** [CANDY-LINE/node-red-contrib-cache#3]
As the Cache-in node is designed, it becomes mandatory to have a switch or function node just after to manage the two cases:
* There was a cache entry ==> Continue with flow
* There was no cache entry ==> Generate data from external store or custom logic

If would save a bit of configuration and make the flow more readable to directly be able to have 2 outputs on the cache-in node

**Comment by dbaba** [comment]
Thank you for the request and sorry for late response.

I introduced a new option to allow the node to propagate an incoming msg to the second port on a cache miss.
The feature is disabled by default but can be enabled on the Cache In configuration dialog.
Try [v2.0.0](https://github.com/CANDY-LINE/node-red-contrib-cache/releases/tag/2.0.0) for the new feature.

**Comment by hubertguillemain** [comment]
Sorry for the late reply here as well - Thanks a lot for the fix, works perfectly :)
